# Generated by Django 6.0.2 on 2026-02-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique region identifier (e.g., 'us', 'jp', 'kr')", max_length=10, unique=True)),
                ('name', models.CharField(help_text="Human-readable region name (e.g., 'United States')", max_length=100)),
                ('default_locale', models.CharField(help_text="Default locale for this region (e.g., 'en-US', 'ja-JP')", max_length=10)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this region is active')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='TranslationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_enabled', models.BooleanField(default=True, help_text='Master switch for translation worker')),
                ('default_provider', models.CharField(choices=[('deepl', 'DeepL'), ('openai', 'OpenAI')], default='deepl', help_text='Primary translation provider (DeepL recommended for quality)', max_length=20)),
                ('canonical_locale_for_analysis', models.CharField(default='en-US', help_text='Base language for trend analysis (LOCKED to en-US)', max_length=10)),
                ('force_canonical_translation', models.BooleanField(default=True, help_text='Always create en-US translation when original_locale != en-US')),
                ('enabled_locales', models.JSONField(blank=True, default=list, help_text='Additional locales to translate to (beyond canonical en-US)')),
                ('max_chars_per_request', models.IntegerField(default=5000, help_text='Maximum characters per translation request (rate limiting)')),
            ],
            options={
                'verbose_name': 'Translation Settings',
                'verbose_name_plural': 'Translation Settings',
            },
        ),
        migrations.CreateModel(
            name='TrendSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique identifier within region (e.g., 'reddit_hot')", max_length=100)),
                ('platform', models.CharField(help_text="Platform name (e.g., 'reddit', 'youtube')", max_length=50)),
                ('surface_type', models.CharField(choices=[('ranking', 'Ranking Surface'), ('sampler', 'Feed Sampler'), ('search', 'Search Trends'), ('news', 'News Top Stories')], help_text='Type of trend surface', max_length=20)),
                ('bucket', models.CharField(choices=[('hot_now', 'Hot Now'), ('rising', 'Rising'), ('category_tech', 'Tech'), ('category_sports', 'Sports'), ('category_entertainment', 'Entertainment'), ('category_finance', 'Finance'), ('category_gaming', 'Gaming'), ('category_lifestyle', 'Lifestyle'), ('category_science', 'Science'), ('category_politics', 'Politics'), ('region_local', 'Region Local'), ('evergreen', 'Evergreen')], default='hot_now', help_text='Diversity bucket assignment (product constraint: no bucket > 40%)', max_length=50)),
                ('bucket_weight', models.FloatField(default=1.0, help_text='Weight for bucket balancing (higher = more priority). From /tmp/t9')),
                ('entrypoint', models.CharField(help_text="Python import path to collector (e.g., 'crawler_surfaces.reddit_hot:collect')", max_length=200)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this surface is active')),
                ('poll_interval_seconds', models.IntegerField(default=3600, help_text='How often to collect from this surface (in seconds)')),
                ('max_items_per_run', models.IntegerField(default=200, help_text='Maximum items to collect per execution')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Surface-specific configuration passed to collector')),
                ('last_cursor', models.TextField(blank=True, help_text='Pagination cursor from last run', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this surface last executed (from /tmp/t8)', null=True)),
                ('last_success_at', models.DateTimeField(blank=True, help_text='When this surface last succeeded (from /tmp/t8)', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message (from /tmp/t8)', null=True)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='When to run next (deprecated, calculated from poll_interval)', null=True)),
                ('region', models.ForeignKey(help_text='Region this surface belongs to', on_delete=django.db.models.deletion.CASCADE, to='crawler_admin.region')),
            ],
            options={
                'verbose_name': 'Trend Surface',
                'verbose_name_plural': 'Trend Surfaces',
                'ordering': ['region', 'key'],
            },
        ),
        migrations.CreateModel(
            name='TrendItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text="Platform's unique ID (for reference)", max_length=255, null=True)),
                ('canonical_hash', models.CharField(db_index=True, help_text='SHA256 hash for deduplication (hash of normalized title + URL)', max_length=64)),
                ('title_original', models.TextField(help_text='Original title in source language')),
                ('description_original', models.TextField(blank=True, help_text='Original description/snippet (if available)', null=True)),
                ('original_locale', models.CharField(help_text="Locale of original content (e.g., 'ja-JP')", max_length=10)),
                ('url', models.TextField(help_text='Link to original content')),
                ('rank_position', models.IntegerField(blank=True, help_text='Position in ranking (1=top). MORE important than timestamps! (from /tmp/t9)', null=True)),
                ('engagement_signals', models.JSONField(blank=True, default=dict, help_text='Platform engagement data (upvotes, views, likes, etc.). Required! (from /tmp/t9)')),
                ('bucket', models.CharField(help_text='Bucket copied from surface at collection time (for diversity tracking)', max_length=50)),
                ('published_at', models.DateTimeField(blank=True, help_text='When content was published (less important than rank_position)', null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True, help_text='When we collected this item')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Complete platform response. NEVER throw away data! (from /tmp/t9)')),
                ('region', models.ForeignKey(help_text='Region this item belongs to', on_delete=django.db.models.deletion.CASCADE, to='crawler_admin.region')),
                ('surface', models.ForeignKey(help_text='Surface that collected this item', on_delete=django.db.models.deletion.CASCADE, to='crawler_admin.trendsurface')),
            ],
            options={
                'verbose_name': 'Trend Item',
                'verbose_name_plural': 'Trend Items',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(help_text='When execution started')),
                ('finished_at', models.DateTimeField(blank=True, help_text='When execution finished (null if still running)', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], help_text='Success or failure status', max_length=20)),
                ('fetched_count', models.IntegerField(default=0, help_text='Items returned by collector API')),
                ('stored_new_count', models.IntegerField(default=0, help_text='New items inserted to database')),
                ('deduped_count', models.IntegerField(default=0, help_text='Duplicate items skipped')),
                ('error_message', models.TextField(blank=True, help_text='Error details if execution failed', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('surface', models.ForeignKey(help_text='Surface that was executed', on_delete=django.db.models.deletion.CASCADE, to='crawler_admin.trendsurface')),
            ],
            options={
                'verbose_name': 'Crawl Run',
                'verbose_name_plural': 'Crawl Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(help_text="Target locale (e.g., 'en-US', 'ja-JP')", max_length=10)),
                ('title', models.TextField(help_text='Translated title')),
                ('description', models.TextField(blank=True, help_text='Translated description (if original had one)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', help_text='Translation workflow state', max_length=20)),
                ('provider', models.CharField(choices=[('deepl', 'DeepL'), ('openai', 'OpenAI')], help_text='Which translation API was used', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if translation failed', null=True)),
                ('translated_at', models.DateTimeField(blank=True, help_text='When translation completed', null=True)),
                ('item', models.ForeignKey(help_text='Item this translation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='crawler_admin.trenditem')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['item', 'locale'],
                'indexes': [models.Index(fields=['status'], name='crawler_adm_status_c9c1fa_idx'), models.Index(fields=['locale', 'status'], name='crawler_adm_locale_6a889a_idx')],
                'unique_together': {('item', 'locale')},
            },
        ),
        migrations.AddIndex(
            model_name='trendsurface',
            index=models.Index(fields=['enabled', 'next_run_at'], name='crawler_adm_enabled_26001e_idx'),
        ),
        migrations.AddIndex(
            model_name='trendsurface',
            index=models.Index(fields=['region', 'bucket'], name='crawler_adm_region__e2dee5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trendsurface',
            unique_together={('region', 'key')},
        ),
        migrations.AddIndex(
            model_name='trenditem',
            index=models.Index(fields=['region', '-collected_at'], name='crawler_adm_region__cda4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='trenditem',
            index=models.Index(fields=['canonical_hash'], name='crawler_adm_canonic_d5e5db_idx'),
        ),
        migrations.AddIndex(
            model_name='trenditem',
            index=models.Index(fields=['bucket', '-collected_at'], name='crawler_adm_bucket_8236db_idx'),
        ),
        migrations.AddIndex(
            model_name='trenditem',
            index=models.Index(fields=['rank_position'], name='crawler_adm_rank_po_73e010_idx'),
        ),
        migrations.AddIndex(
            model_name='trenditem',
            index=models.Index(fields=['surface', '-collected_at'], name='crawler_adm_surface_869dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlrun',
            index=models.Index(fields=['surface', '-created_at'], name='crawler_adm_surface_7dbd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlrun',
            index=models.Index(fields=['status', '-created_at'], name='crawler_adm_status_07fad4_idx'),
        ),
    ]
