# Generated by Django 4.2.28 on 2026-02-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0003_add_translation_query_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="trenditemtranslation",
            name="crawler_admin_translation_query_idx",
        ),
        migrations.AlterField(
            model_name="translationsettings",
            name="default_provider",
            field=models.CharField(
                choices=[
                    ("deepl", "DeepL"),
                    ("openai", "OpenAI"),
                    ("argostranslate", "Argostranslate (Offline)"),
                    ("none", "No Translation (English variants)"),
                ],
                default="deepl",
                help_text="Primary translation provider (DeepL recommended for quality)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trenditemtranslation",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deepl", "DeepL"),
                    ("openai", "OpenAI"),
                    ("argostranslate", "Argostranslate (Offline)"),
                    ("none", "No Translation (English variants)"),
                ],
                help_text="Which translation API was used",
                max_length=20,
                null=True,
            ),
        ),
    ]
