# Generated by Django 4.2.28 on 2026-02-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crawler_admin",
            "0004_remove_trenditemtranslation_crawler_admin_translation_query_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendsurface",
            name="bucket",
            field=models.CharField(
                choices=[
                    ("hot_now", "Hot Now"),
                    ("rising", "Rising"),
                    ("news", "News"),
                    ("category_tech", "Tech"),
                    ("category_sports", "Sports"),
                    ("category_entertainment", "Entertainment"),
                    ("category_finance", "Finance"),
                    ("category_gaming", "Gaming"),
                    ("category_lifestyle", "Lifestyle"),
                    ("category_science", "Science"),
                    ("category_politics", "Politics"),
                    ("region_local", "Region Local"),
                    ("evergreen", "Evergreen"),
                ],
                default="hot_now",
                help_text="Diversity bucket assignment (product constraint: no bucket > 40%)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trendsurface",
            name="surface_type",
            field=models.CharField(
                choices=[
                    ("ranking", "Ranking Surface"),
                    ("sampler", "Feed Sampler"),
                    ("search", "Search Trends"),
                    ("news", "News Top Stories"),
                    ("rss_feed", "RSS Feed"),
                ],
                help_text="Type of trend surface",
                max_length=20,
            ),
        ),
    ]
