# Generated by Django 4.2.28 on 2026-02-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0005_add_rss_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="trenditem",
            name="canonical_description",
            field=models.TextField(
                blank=True,
                help_text="Canonical (en-US) description for ranking/analysis",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trenditem",
            name="canonical_engine",
            field=models.CharField(
                blank=True,
                help_text="Engine used for canonical translation (deepl, openai, local, none)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trenditem",
            name="canonical_error",
            field=models.TextField(
                blank=True,
                help_text="Error message if canonical translation failed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trenditem",
            name="canonical_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped (already English)"),
                ],
                default="pending",
                help_text="Canonical translation status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trenditem",
            name="canonical_title",
            field=models.TextField(
                blank=True,
                help_text="Canonical (en-US) title for ranking/analysis",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trenditem",
            name="display_description_zh_hans",
            field=models.TextField(
                blank=True,
                help_text="Chinese Simplified (zh-Hans) description for display",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trenditem",
            name="display_engine_zh_hans",
            field=models.CharField(
                blank=True,
                help_text="Engine used for zh-Hans translation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trenditem",
            name="display_status_zh_hans",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped (already native)"),
                ],
                default="pending",
                help_text="zh-Hans translation status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trenditem",
            name="display_title_zh_hans",
            field=models.TextField(
                blank=True,
                help_text="Chinese Simplified (zh-Hans) title for display",
                null=True,
            ),
        ),
    ]
