# Generated by Django 4.2.28 on 2026-04-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0012_human_browsing_simulation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="domainmetrics",
            new_name="crawler_adm_domain_d938a0_idx",
            old_name="crawler_adm_domain_hour_idx",
        ),
        migrations.RenameIndex(
            model_name="domainmetrics",
            new_name="crawler_adm_hour_bu_bb466d_idx",
            old_name="crawler_adm_hour_bu_idx",
        ),
        migrations.RenameIndex(
            model_name="domainpolicy",
            new_name="crawler_adm_circuit_91ea53_idx",
            old_name="crawler_adm_circuit_idx",
        ),
        migrations.RenameIndex(
            model_name="itemderivation",
            new_name="crawler_adm_item_id_2f5487_idx",
            old_name="crawler_admin_itemderivation_lookup_idx",
        ),
        migrations.RenameIndex(
            model_name="itemderivation",
            new_name="crawler_adm_derivat_b000a8_idx",
            old_name="crawler_admin_itemderivation_type_status_idx",
        ),
        migrations.RenameIndex(
            model_name="itemderivation",
            new_name="crawler_adm_target__028e11_idx",
            old_name="crawler_admin_itemderivation_locale_status_idx",
        ),
        migrations.RenameIndex(
            model_name="trenditem",
            new_name="crawler_adm_lang_gr_c5dba9_idx",
            old_name="crawler_admin_trenditem_lang_group_hotness_idx",
        ),
        migrations.RenameIndex(
            model_name="trenditem",
            new_name="crawler_adm_base_la_15e070_idx",
            old_name="crawler_admin_trenditem_base_lang_collected_idx",
        ),
        migrations.RenameIndex(
            model_name="trenditem",
            new_name="crawler_adm_hotness_31bf96_idx",
            old_name="crawler_admin_trenditem_hotness_idx",
        ),
        migrations.RenameIndex(
            model_name="urlcache",
            new_name="crawler_adm_expires_24f067_idx",
            old_name="crawler_adm_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="urlcache",
            new_name="crawler_adm_last_va_d29275_idx",
            old_name="crawler_adm_last_va_idx",
        ),
        migrations.AlterField(
            model_name="itemderivation",
            name="engine",
            field=models.CharField(
                help_text="Engine/provider used (e.g., 'claude')", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="trenditem",
            name="canonical_engine",
            field=models.CharField(
                blank=True,
                help_text="Engine used for canonical translation (claude, none)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trenditemtranslation",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("claude", "Claude CLI"),
                    ("none", "No Translation (English variants)"),
                ],
                help_text="Which translation API was used",
                max_length=20,
                null=True,
            ),
        ),
    ]
