# Generated by Django 4.2.28 on 2026-04-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0015_per_locale_hot_percent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemderivation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Translated Item",
                "verbose_name_plural": "Translated Items",
            },
        ),
    ]
