# Generated by Django 4.2.29 on 2026-04-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0016_alter_itemderivation_options"),
        ("crawler_admin", "0016_summary_status_queued"),
    ]

    operations = []
