# Generated by Django 4.2.28 on 2026-04-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0018_surface_allocation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trenditem",
            name="summary_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued (selected for translation)"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped (no summarizable content)"),
                ],
                default="pending",
                help_text="AI summarization status for description_original",
                max_length=20,
            ),
        ),
    ]
