# Generated by Django 4.2.28 on 2026-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0019_alter_trenditem_summary_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendsurface",
            name="healthy",
            field=models.BooleanField(
                default=True,
                help_text="False when surface has 3+ consecutive runs with 0 items collected",
            ),
        ),
        migrations.AddField(
            model_name="trendsurface",
            name="unhealthy_streak",
            field=models.IntegerField(
                default=0, help_text="Consecutive runs with 0 items collected"
            ),
        ),
    ]
