# Generated by Django 4.2.28 on 2026-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0020_add_healthy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="trenditem",
            name="content_regions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Regions the content is ABOUT (multi-label). Empty list = not yet classified or no specific region. Example: ['cn', 'us'] for US-China trade war article.",
            ),
        ),
        migrations.AddField(
            model_name="trenditem",
            name="primary_region",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Main region the content is about (first non-US from content_regions). Used for fast indexed queries.",
                max_length=10,
                null=True,
            ),
        ),
    ]
