# Generated by Django 4.2.28 on 2026-04-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0021_trenditem_content_regions_trenditem_primary_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="trenditem",
            name="region_classified_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When region classification was last attempted (by heuristic or LLM). NULL = never tried. Prevents re-processing items that LLM classified as no-region.",
                null=True,
            ),
        ),
    ]
