# Generated by Django 4.2.28 on 2026-04-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0028_seed_top_comments_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="trenditem",
            name="region_classification_method",
            field=models.CharField(
                blank=True,
                help_text="Which method produced the region result: heuristic = keyword/rule pass succeeded; llm = sent to LLM (region found or not); skipped = heuristic failed and below hotness threshold (LLM not called). NULL = legacy item classified before this field was added.",
                max_length=16,
                null=True,
            ),
        ),
    ]
