# Generated by Django 4.2.28 on 2026-04-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_admin", "0029_add_region_classification_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemderivation",
            name="engine",
            field=models.CharField(
                help_text="Engine/provider used (e.g., 'claude', 'BAAI/bge-small-en-v1.5')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="trenditem",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Platform's unique ID (for reference)",
                max_length=2048,
                null=True,
            ),
        ),
    ]
