# Generated by Django 4.2.28 on 2026-02-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'GPT-4o Mini')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        default="openai",
                        help_text="LLM provider",
                        max_length=20,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="Model identifier (e.g., 'gpt-4o-mini', 'claude-3-haiku')",
                        max_length=100,
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.3,
                        help_text="Sampling temperature (0.0-1.0, lower = more deterministic)",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=1000, help_text="Maximum tokens in response"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this model is available for use",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this model as default for OpenAI engine",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this model (cost, quality, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Model",
                "verbose_name_plural": "LLM Models",
                "ordering": ["provider", "name"],
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for identification",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "translation_type",
                    models.CharField(
                        choices=[
                            ("canonical", "Canonical (Semantic Normalization)"),
                            ("display", "Display (Human-Readable)"),
                        ],
                        help_text="Type of translation this template is for",
                        max_length=20,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="System role message (defines translator behavior)"
                    ),
                ),
                (
                    "developer_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Developer role message (optional, for additional instructions)",
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="User message template with {variables}"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Notes about when to use this template"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is available for use",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this template as default for its translation type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prompt Template",
                "verbose_name_plural": "Prompt Templates",
                "ordering": ["translation_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="TranslationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canonical_engine",
                    models.CharField(
                        choices=[
                            ("deepl", "DeepL"),
                            ("openai", "OpenAI"),
                            ("local", "Argostranslate (Offline)"),
                        ],
                        default="deepl",
                        help_text="Engine for canonical (en-US) translations used in ranking/analysis",
                        max_length=20,
                    ),
                ),
                (
                    "display_engine",
                    models.CharField(
                        choices=[
                            ("deepl", "DeepL"),
                            ("openai", "OpenAI"),
                            ("local", "Argostranslate (Offline)"),
                        ],
                        default="deepl",
                        help_text="Engine for display translations (human-readable UI)",
                        max_length=20,
                    ),
                ),
                (
                    "fallback_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of fallback engines: ['deepl', 'openai', 'local']",
                    ),
                ),
                (
                    "enable_translation",
                    models.BooleanField(
                        default=True, help_text="Master switch for translation worker"
                    ),
                ),
                (
                    "production_mode",
                    models.BooleanField(
                        default=True,
                        help_text="If True, local engine is disabled (API-only mode)",
                    ),
                ),
                (
                    "canonical_locale",
                    models.CharField(
                        default="en-US",
                        help_text="Base language for trend analysis (LOCKED to en-US)",
                        max_length=10,
                    ),
                ),
                (
                    "enabled_locales",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional locales to translate to (e.g., ['zh-Hans'])",
                    ),
                ),
                (
                    "max_chars_per_request",
                    models.IntegerField(
                        default=5000,
                        help_text="Maximum characters per translation request",
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=10,
                        help_text="Number of items to process per worker cycle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Translation Configuration",
                "verbose_name_plural": "Translation Configuration",
            },
        ),
    ]
