# Generated by Django 4.2.28 on 2026-04-01 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translation", "0006_add_claude_engine"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PromptTemplate",
        ),
        migrations.AlterField(
            model_name="translationconfig",
            name="canonical_model",
            field=models.ForeignKey(
                blank=True,
                help_text="LLM model config (not used by Claude CLI engine)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="canonical_configs",
                to="translation.llmmodelconfig",
            ),
        ),
        migrations.AlterField(
            model_name="translationconfig",
            name="display_model",
            field=models.ForeignKey(
                blank=True,
                help_text="LLM model config (not used by Claude CLI engine)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="display_configs",
                to="translation.llmmodelconfig",
            ),
        ),
        migrations.AlterField(
            model_name="translationconfig",
            name="fallback_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of fallback engines: ['claude']",
            ),
        ),
    ]
