# Generated by Django 4.2.28 on 2026-04-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation", "0008_translationconfig_prompts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationconfig",
            name="canonical_batch_prompt",
            field=models.TextField(
                default='Translate {source_locale}→en-US. Platform: {platform}. Literal, consistent.\nReturn JSON only: {"title": "...", "description": "..."}\n\nTitle: {title}\nDescription: {description}',
                help_text="Prompt for canonical (en-US) batch translation (title + description). Variables: {source_locale}, {target_locale}, {platform}, {title}, {description}",
            ),
        ),
        migrations.AlterField(
            model_name="translationconfig",
            name="canonical_prompt",
            field=models.TextField(
                default="Translate {source_locale}→en-US. Platform: {platform}. Literal, machine-consistent.\n\n{text}",
                help_text="Prompt for canonical (en-US) single-text translation. Variables: {source_locale}, {target_locale}, {platform}, {text}",
            ),
        ),
        migrations.AlterField(
            model_name="translationconfig",
            name="display_batch_prompt",
            field=models.TextField(
                default='Translate {source_locale}→{target_locale}. Platform: {platform}. Natural, preserve tone.\nReturn JSON only: {"title": "...", "description": "..."}\n\nTitle: {title}\nDescription: {description}',
                help_text="Prompt for display batch translation (title + description). Variables: {source_locale}, {target_locale}, {platform}, {title}, {description}",
            ),
        ),
        migrations.AlterField(
            model_name="translationconfig",
            name="display_prompt",
            field=models.TextField(
                default="Translate {source_locale}→{target_locale}. Platform: {platform}. Natural, preserve tone.\n\n{text}",
                help_text="Prompt for display single-text translation. Variables: {source_locale}, {target_locale}, {platform}, {text}",
            ),
        ),
    ]
